spring.application.name=NotificationService

#Config mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thucbq.goldenbee@gmail.com
spring.mail.password=wfxj mnqp edum hgf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true