version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/user_service
      - SPRING_DATASOURCE_USERNAME=dino@admin
      - SPRING_DATASOURCE_PASSWORD=dinone@0310
